---
# tasks file for pentester-ansible
- name: Include common
  include_tasks: common.yml

- name: Include recon
  include_tasks: recon.yml

- name: Include web
  include_tasks: web.yml

- name: Include vpn
  include_tasks: vpn.yml

- name: Include privesc
  include_tasks: privesc.yml